name: Auto Magisk Files Provider
on:
  release:
    types: [published]
  push:
    tags:
      - "v*"
  #  branches:
  #    - master
  schedule:
    - cron: 0 */8 * * *
  watch:
    types: [started]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
        #   persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        #   fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Download Json
        run: |
          mkdir offical
          mkdir delta
          mkdir alpha
          mkdir lite
          mkdir monet
          echo 'Offical Start'
          wget https://raw.githubusercontent.com/topjohnwu/magisk-files/master/stable.json -O ./offical/stable.json
          wget https://raw.githubusercontent.com/topjohnwu/magisk-files/master/beta.json -O ./offical/beta.json
          wget https://raw.githubusercontent.com/topjohnwu/magisk-files/master/canary.json -O ./offical/canary.json
          wget https://raw.githubusercontent.com/topjohnwu/magisk-files/master/debug.json -O ./offical/debug.json
          echo 'Offical End'
          echo 'Delta Start'
          wget https://raw.githubusercontent.com/HuskyDG/magisk-files/main/stable.json -O ./delta/stable.json
          wget https://raw.githubusercontent.com/HuskyDG/magisk-files/main/beta.json -O ./delta/beta.json
          wget https://raw.githubusercontent.com/HuskyDG/magisk-files/main/canary.json -O ./delta/canary.json
          wget https://raw.githubusercontent.com/HuskyDG/magisk-files/main/debug.json -O ./delta/debug.json
          echo 'Delta End'
          echo 'Alpha Start'
          wget https://raw.githubusercontent.com/vvb2060/magisk_files/alpha/alpha.json -O ./alpha/alpha.json
          echo 'Alpha End'
          echo 'Monet Start'
          wget https://raw.githubusercontent.com/datnerdguy/magisk-monet-files/master/stable.json -O ./monet/stable.json
          wget https://raw.githubusercontent.com/datnerdguy/magisk-monet-files/master/beta.json -O ./monet/beta.json
          wget https://raw.githubusercontent.com/datnerdguy/magisk-monet-files/master/canary.json -O ./monet/canary.json
          wget https://raw.githubusercontent.com/datnerdguy/magisk-monet-files/master/debug.json -O ./monet/debug.json
          echo 'Monet End'
          
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "raw.githubusercontent.com"
          replace: "raw.fastgit.org"
          include: ".json"

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "github.com"
          replace: "download.fastgit.org"
          include: ".json"

      - name: Commit files
        run: |
          {
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add .
              git commit -m "$(date "+%Y-%m-%d %H:%M:%S") UTC" -a
              if [ $? -eq 0 ]; then
                  date >>RunDate.txt
                  git commit -m "$(date "+%Y-%m-%d %H:%M:%S" UTC)" -a
                  git push
              else
                  echo No Update
              fi
          } || {
              echo Execution Failed >RunDate.txt
              exit 1
          }
